data:
  params:
    num_workers: 4
    pin_memory: true
    train:
      target: calo_ldm.data.CaloHDF5
      params:
        file_path: "xxx.hdf5"
        do_rotations: false
    validation:
      target: calo_ldm.data.CaloHDF5
      params:
        file_path: "xxx.hdf5"
    batch_size: 256
  target: calo_ldm.data.DataModuleFromConfig
model:
  base_learning_rate: 3.0e-06
  monitor: val/rec_loss
  target: calo_ldm.models.VQModel
  params:
    legacy: True
    embed_dim: 192
    n_embed: 1024
    cond_dim: 1
    z_padding_strategy: null
    log_scale_params:
    - 0
    - 40000
    - 10
    reco_normalization: R
    disc_normalization: U
    learn_R: false
    dataset_name: '3'
    encoder_config:
      target: calo_ldm.models.Encoder
      params:
        ch_in: 18
        ch_out: 256
        conv_spec:
        - 'zpad  : 1 : 2'
        - 'cconv : k33 :     : c32'
        - 'cconv : k33 :     : c32'
        - 'fftd  : 16 : 2'
        - 'cconv : k33 : s21  : c64'
        - 'cconv : k33 :      : c64'
        - 'fftd  : 12 : 2'
        - 'cconv : k33 :     : c128'
        - 'cconv : k33 :     : c128'
        - 'fftd  : 8 : 2'
        - 'cconv : k33 :     : c256'
        cond_dim: 1
        log_scale_params:
        - 0
        - 40000
        - 10
        z_pad: null
        z_padding_strategy: null
    decoder_config:
      target: calo_ldm.models.Decoder
      params:
        ch_in: 256
        ch_out: 18
        conv_spec:
        - 'cconvT : k33 :     : c128'
        - 'ffti  : 8 : 2'
        - 'cconvT : k33 :     : c128'
        - 'cconvT : k33 :     : c64'
        - 'ffti  : 12 : 2'
        - 'cconvT : k33 :     : c64'
        - 'cconvT : k33 : s21 : c32'
        - 'ffti  : 16 : 2'
        - 'cconvT : k33 :     : c32'
        - 'cconvT : k33 :     : c32'
        - 'zcrop : 1 : 1'
        output_activation: voxel_relu_expm1_max
        R_activation: softplus
        cond_dim: 1
        learn_R: false
        z_pad: null
        z_padding_strategy: null
    loss_config:
      target: calo_ldm.losses.CombinedLoss
      params:
        pixel_power: 2
        pixel_weight: 1
        disc_conditional: false
        disc_in_channels: 9
        disc_start: 500
        disc_weight: 0.8
        codebook_weight: 1.0
        perceptual_weight: 0
        R1_weight: 0.1
        R2_weight: 0
        dataset_name: '3'
        disc_config:
          target: calo_ldm.models.Discriminator
          params:
            pooling: null
            cond_dim: 1
            ch_in: 18
            conv_spec:
            - 'cconv : k33 :     : c32'
            - 'cconv : k33 : s21 : c64'
            - 'fftd : 18'
            - 'cconv : k33 :     : c64'
            - 'cconv : k33 : s21 : c128'
            - 'fftd : 16'
            - 'cconv : k33 :     : c128'
            - 'fftd : 8'
            - 'cconv : k33 :     : c256'
            log_scale_params:
            - 0
            - 40000
            - 10
        perceptual_config: null
        cond_dim: 1
        n_embed: 1024
        log_scale_params:
        - 0
        - 40000
        - 10
        learn_R: false
        disc_normalization: U
        reco_normalization: R
        unpad_z: null
