data:
  params:
    num_workers: 0
    pin_memory: true
    train:
      target: calo_ldm.data.CaloHDF5
      params:
        file_path: "xxx.hdf5"
        do_rotations: false
    validation:
      target: calo_ldm.data.CaloHDF5
      params:
        file_path: "xxx.hdf5"
    batch_size: 256
    batched_indices: true
  target: calo_ldm.data.DataModuleFromConfig
model:
  params:
    sequence_shape: 
    - 13
    - 14
    codebook_size: 1024
    vq_config:
      model_config: config/ds3_step1.yaml
      checkpoint: models/ds3/checkpoints/epoch.ckpt
    n_layer: 1
    n_head: 1
    n_embd: 16
    predict_R: true
    R_bits: 10
    R_max: 1.7
  base_learning_rate: 3.0e-06
  target: calo_ldm.models.CondGPT
