data:
  params:
    num_workers: 0
    pin_memory: true
    train:
      target: calo_ldm.data.CaloHDF5
      params:
        load_partial: 10000
        do_rotations: true
        do_inversions: true
        file_path: /hpcfs/cepc/higgs/liuqibin/CALO/calo-data/ds3/dataset_3_12.hdf5
    validation:
      target: calo_ldm.data.CaloHDF5
      params:
        load_partial: 10000
        file_path: /hpcfs/cepc/higgs/liuqibin/CALO/calo-data/ds3/dataset_3_34.hdf5
    batch_size: 256
  target: calo_ldm.data.DataModuleFromConfig
model:
  base_learning_rate: 3.0e-06
  monitor: val/loss
  target: calo_ldm.models.CondGPT
  params:
    codebook_size: 1024
    sequence_shape:
    - 24
    - 26
    n_layer: 1
    n_head: 1
    n_embd: 128
    predict_R: true
    R_seq_len: 2
    R_max: 3
    R_renorm: false
    debug_mode: 2
    cond_bins: 0
    vq_config:
      model_config: config/ds3_norm_step1.yaml
      checkpoint: models/ds3_norm/checkpoints/epoch.ckpt
    pure_mode: false
    record_freq: 20
